/***********************************************************************/
/*                                                                     */
/*  FILE        :hew_lowio_test.c                                      */
/*  DATE        :Sun, Feb 24, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "stdio.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	char* aaa = 0;
	char* bbb = 0;

	printf("Hello world\n");

	aaa = (char*)malloc((size_t)20);
	bbb = (char*)malloc((size_t)40);
	
	aaa[0] = 'A';

	free(aaa);
	free(bbb);
//	sbrk(test);
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
