/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Sun, Feb 24, 2013                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


void HardwareSetup(void)
{
// Initialize routine
/*
  P1DDR = 0;
  P1DR.BYTE = 0;
  P1DR.BIT.B7 = 1;
  P1DR.BIT.B6 = 1;
  P1DR.BIT.B5 = 1;
  P1DR.BIT.B4 = 1;
  P1DR.BIT.B3 = 1;
  P1DR.BIT.B2 = 1;
  P1DR.BIT.B1 = 1;
  P1DR.BIT.B0 = 1;
*/
}
