/***********************************************************************/
/*                                                                     */
/*  FILE        :uart_test.c                                           */
/*  DATE        :Fri, Feb 08, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "3069f_sci.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	char c;

	sci_init(SCI_NO_1, BitRate_type_br9600);

	sci_write(SCI_NO_1, 'A');
	sci_write_str(SCI_NO_1,"Hello world!!\n");

	while(1)
	{
		c = sci_read_byte(SCI_NO_1);
		sci_write(SCI_NO_1, c);
	}

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
