#include <asm.h>
#include <asm_common.h>
#include <asm_depend.h>
#include <basic.h>
#include <bitop.h>
#include <check.h>
#include <config.h>
#include <cpuattr.h>
#include <cpudef.h>
#include <cpu_calls.h>
#include <cpu_conf.h>
#include <cpu_insn.h>
#include <cpu_status.h>
#include <cpu_task.h>
#include <dbgspt.h>
#include <dbgspt_common.h>
#include <dbgspt_depend.h>
#include <debug.h>
#include <device.h>
#include <errno.h>
#include <eventflag.h>
#include <hwconfig.h>
#include <imalloc.h>
#include <inittask_def.h>
#include <isyscall.h>
#include <isysconf.h>
#include <kernel.h>
#include <libstr.h>
#include <libstr_config.h>
#include <libtk_config.h>
#include <limits.h>
#include <longlong.h>
#include <machine.h>
#include <machine_common.h>
#include <machine_depend.h>
#include <mailbox.h>
#include <memory.h>
#include <mempfix.h>
#include <mempool.h>
#include <messagebuf.h>
#include <misc_calls.h>
#include <mutex.h>
#include <offset.h>
#include <patch.h>
#include <profile.h>
#include <profile_common.h>
#include <profile_depend.h>
#include <queue.h>
#include <ready_queue.h>
#include <rendezvous.h>
#include <semaphore.h>
#include <stdtype.h>
#include <str_align.h>
#include <str_align_common.h>
#include <str_align_depend.h>
#include <subsystem.h>
#include <syscall.h>
#include <syscall_common.h>
#include <sysdef.h>
#include <sysdef_common.h>
#include <sysdef_depend.h>
#include <sysinfo.h>
#include <sysinfo_common.h>
#include <sysinfo_depend.h>
#include <sysinit.h>
#include <syslib.h>
#include <syslib_common.h>
#include <syslib_depend.h>
#include <sysmain.h>
#include <sysmgr.h>
#include <task.h>
#include <task_sync.h>
#include <tdfncd.h>
#include <tdfncd16.h>
#include <tdfncd32.h>
#include <tdsvcproxy.h>
#include <tdsvctbl.h>
#include <timer.h>
#include <time_calls.h>
#include <tkdev_conf.h>
#include <tkdev_timer.h>
#include <tkernel.h>
#include <tkfncd.h>
#include <tkfncd16.h>
#include <tkfncd32.h>
#include <tksvcproxy.h>
#include <tksvctbl.h>
#include <tk_typedef.h>
#include <tmonitor.h>
#include <util.h>
#include <utk_config.h>
#include <utk_config_depend.h>
#include <utk_config_func.h>
#include <wait.h>
#include <winfo.h>

#include <W:\src\kernel\tkernel\kernel_cmn\bitop.c>
#include <W:\src\kernel\tkernel\kernel_cmn\device.c>
#include <W:\src\kernel\tkernel\kernel_cmn\deviceio.c>
#include <W:\src\kernel\tkernel\kernel_cmn\eventflag.c>
#include <W:\src\kernel\tkernel\kernel_cmn\fastlock.c>
#include <W:\src\kernel\tkernel\kernel_cmn\fastmlock.c>
#include <W:\src\kernel\tkernel\kernel_cmn\klock.c>
#include <W:\src\kernel\tkernel\kernel_cmn\mailbox.c>
#include <W:\src\kernel\tkernel\kernel_cmn\memory.c>
#include <W:\src\kernel\tkernel\kernel_cmn\mempfix.c>
#include <W:\src\kernel\tkernel\kernel_cmn\mempool.c>
#include <W:\src\kernel\tkernel\kernel_cmn\messagebuf.c>
#include <W:\src\kernel\tkernel\kernel_cmn\misc_calls.c>
#include <W:\src\kernel\tkernel\kernel_cmn\mutex.c>
#include <W:\src\kernel\tkernel\kernel_cmn\objname.c>
#include <W:\src\kernel\tkernel\kernel_cmn\rendezvous.c>
#include <W:\src\kernel\tkernel\kernel_cmn\semaphore.c>
#include <W:\src\kernel\tkernel\kernel_cmn\subsystem.c>
#include <W:\src\kernel\tkernel\kernel_cmn\task.c>
#include <W:\src\kernel\tkernel\kernel_cmn\task_manage.c>
#include <W:\src\kernel\tkernel\kernel_cmn\task_sync.c>
#include <W:\src\kernel\tkernel\kernel_cmn\timer.c>
#include <W:\src\kernel\tkernel\kernel_cmn\time_calls.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tkstart.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_command.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_exit.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_getchar.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_getline.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_monitor.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_printf.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_putchar.c>
#include <W:\src\kernel\tkernel\kernel_cmn\tm_putstring.c>
#include <W:\src\kernel\tkernel\kernel_cmn\wait.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\clock_mode.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\cpu_calls.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\cpu_init.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\devinit.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\inittask_def.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\inittask_main.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\int.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\patch.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\power.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\sio.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\sysinit_main.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\sysstartup.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\tkdev_init.c>
#include <W:\src\kernel\tkernel\rl78g13_r5f100adasp\usermain.c>
