/***********************************************************************/
/*                                                                     */
/*  FILE        :lowio_test.c                                          */
/*  DATE        :Sun, Feb 24, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "stdio.h"
#include "3069f_sci.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	printf("Hello world!!\n");
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
