/***********************************************************************/
/*                                                                     */
/*  FILE        :hew_lowio_test.c                                      */
/*  DATE        :Thu, Feb 21, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "stdio.h"
#include "3069f_sci.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	char c;
	sci_init(SCI_NO_1, BitRate_type_br19200);

	printf("hello world!!\n");

	while(1)
	{
		c = getchar();
		printf("%x", c);
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
