/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Thu, Feb 21, 2013                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/




#include "iodefine.h"
#include "3069f_sci.h"
#include "dram.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


void HardwareSetup(void)
{
// Initialize routine
	sci_init(SCI_NO_1, BitRate_type_br9600);
	exp_memory_init();

}
