/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Thu, Feb 21, 2013                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 3
