/***********************************************************************/
/*                                                                     */
/*  FILE        :elf_test.c                                            */
/*  DATE        :Thu, Feb 21, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  
#include "3069f_sci.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	sci_init(SCI_NO_1, BitRate_type_br19200);
	sci_write_str(SCI_NO_1, "hello from elf mod!!\n");
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
