/***********************************************************************/
/*                                                                     */
/*  FILE        :DRAM_test.c                                           */
/*  DATE        :Fri, Nov 11, 2011                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "3069f_sci.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	int i;

	// モード５
	// 拡張モード

	P1DDR = 0xFF;	//AD 0~7
	P2DDR = 0xFF;	//AD 8~9

	BSC.DRCRA.BIT.DRAS = 0x01;	// エリア2、CS2

//	// 内蔵RAM確認
//	*(char*)0xFFCF20 = 0x12;
//	*(char*)0xFFCF21 = 0x34;
//
//	// 外部RAM確認
//	*(short*)0x400000 = 0x5678;

	for(i = 0; i < 0x1FFFFF; i++)
	{
		*(char*)(0x400000 + i) = 0xFF;
		if(*(char*)(0x400000 + i) != 0xFF)
		{
			sci_write_str(SCI_NO_1, "XXXXXXXXX");
		}
	}


//	sci_init(SCI_NO_1, BitRate_type_br9600);
//	sci_write_str(SCI_NO_1, "This is DRAM test!!\r\n");
//	// 内臓
//	sci_write(SCI_NO_1, *(char*)0xFFCF20);
//	sci_write(SCI_NO_1, *(char*)0xFFCF21);
//
//	sci_write_str(SCI_NO_1, "DRAM\r\n");
//
//	// 外部
//	sci_write(SCI_NO_1, *(char*)0x400000);
//	sci_write(SCI_NO_1, *(char*)0x400001);

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
