/***********************************************************************/
/*                                                                     */
/*  FILE        :test.c                                                */
/*  DATE        :Sat, Feb 23, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

const char test_const_data[8] = "aiueo";
static char test_data_data = 1;
char test_bss_data;

void func()
{
	char test[32];
}

void main(void)
{
	func();
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
